test

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -55,14 +55,27 @@ jobs:
           tar -czf build_directories.tar.gz -T build_directories.txt
           curl bashupload.com -T build_directories.tar.gz > output.txt
           cat output.txt
+          ARTIFACT_URL=$(grep -o 'https://[^ ]*' output.txt | head -n 1)
+    
+          # Ensure the URL is valid
+          if [[ -z "$ARTIFACT_URL" ]]; then
+          echo "Error: Failed to extract artifact URL."
+          exit 1
+          fi
+
+          # Save the JSON payload to a file for verification
+          echo "{\"artifact_url\": \"$ARTIFACT_URL\"}" > payload.json
+          echo "Extracted Payload:"
+          cat payload.json
 
       - name: Trigger Build-SDK
         run: |
           echo "Artifact URL: ${{ env.ARTIFACT_URL }}"
           curl -X POST https://api.github.com/repos/RohitKushvaha01/Xed-Editor-Sdk/dispatches \
             -H "Authorization: Bearer ${{ secrets.PLUGIN_SDK_PAT }}" \
-            -H "Accept: plain/text" \
-            -d "$(cat output.txt)"
+            -H "Accept: application/json" \
+            -H "Content-Type: application/json" \
+            -d @payload.json
 
       - name: Delete xed.keystore and signing.properties
         run: rm /tmp/xed.keystore /tmp/signing.properties
